# Pulls the latest NGINX image from Docker Hub
FROM nginx:latest
# Changes the working directory in the container, this directory is a a common location where web content is served from within the Nginx web server
WORKDIR /usr/share/nginx/html/
# Copies the current directories HTML file to the NGINX web server 
COPY index.html index.html
